version: "3.9"

services:

  postgres:

    image: postgres:16

    container_name: sentinel-postgres

    restart: always

    environment:

      POSTGRES_USER: sentinel

      POSTGRES_PASSWORD: sentinel123

      POSTGRES_DB: sentinel

    ports:

      - "5432:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

  redis:

    image: redis:7

    container_name: sentinel-redis

    restart: always

    ports:

      - "6379:6379"

  api:

    build: ./apps/api

    container_name: sentinel-api

    restart: always

    ports:

      - "8000:8000"

    depends_on:

      - postgres
      - redis

    env_file:

      - .env

  web:

    build: ./apps/web

    container_name: sentinel-web

    restart: always

    ports:

      - "3000:3000"

    depends_on:

      - api

    env_file:

      - .env

volumes:

  postgres_data: